-- =========================================================
-- APLICACION CRUD ORACLE 19c
-- PROCEDIMIENTOS ALMACENADOS + TRIGGER
-- =========================================================

-- =========================================================
-- 1. ELIMINAR OBJETOS SI EXISTEN
-- =========================================================

BEGIN
    EXECUTE IMMEDIATE 'DROP TRIGGER TRG_REGISTRO_50';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/
    
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LOG_REGISTRO_50 CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE EMPLEADOS_H CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP PROCEDURE SP_INSERTAR_EMPLEADO';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP PROCEDURE SP_LISTAR_EMPLEADOS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP PROCEDURE SP_ACTUALIZAR_EMPLEADO';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP PROCEDURE SP_ELIMINAR_EMPLEADO';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

COMMIT;

-- =========================================================
-- 2. CREAR TABLA EMPLEADOS
-- =========================================================

CREATE TABLE EMPLEADOS_H (

    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    NOMBRE VARCHAR2(100) NOT NULL,

    CARGO VARCHAR2(100) NOT NULL,

    SALARIO NUMBER(10,2) NOT NULL,

    FECHA_REGISTRO DATE DEFAULT SYSDATE

);

COMMIT;

-- =========================================================
-- 3. TABLA LOG DEL TRIGGER
-- =========================================================

CREATE TABLE LOG_REGISTRO_50 (

    ID_LOG NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    MENSAJE VARCHAR2(300),

    FECHA_LOG DATE DEFAULT SYSDATE

);

COMMIT;

-- =========================================================
-- 4. PROCEDIMIENTO INSERTAR
-- =========================================================

CREATE OR REPLACE PROCEDURE SP_INSERTAR_EMPLEADO(

    P_NOMBRE IN VARCHAR2,
    P_CARGO IN VARCHAR2,
    P_SALARIO IN NUMBER

)
AS
BEGIN

    INSERT INTO EMPLEADOS_H (

        NOMBRE,
        CARGO,
        SALARIO

    )
    VALUES (

        P_NOMBRE,
        P_CARGO,
        P_SALARIO

    );

END;
/

SHOW ERRORS;

COMMIT;

-- =========================================================
-- 5. PROCEDIMIENTO LISTAR
-- =========================================================

CREATE OR REPLACE PROCEDURE SP_LISTAR_EMPLEADOS(

    P_CURSOR OUT SYS_REFCURSOR

)
AS
BEGIN

    OPEN P_CURSOR FOR

    SELECT
        ID,
        NOMBRE,
        CARGO,
        SALARIO,
        FECHA_REGISTRO
    FROM EMPLEADOS_H
    ORDER BY ID;

END;
/

SHOW ERRORS;

COMMIT;

-- =========================================================
-- 6. PROCEDIMIENTO ACTUALIZAR
-- =========================================================

CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_EMPLEADO(

    P_ID IN NUMBER,
    P_NOMBRE IN VARCHAR2,
    P_CARGO IN VARCHAR2,
    P_SALARIO IN NUMBER

)
AS
BEGIN

    UPDATE EMPLEADOS_H
    SET

        NOMBRE = P_NOMBRE,
        CARGO = P_CARGO,
        SALARIO = P_SALARIO

    WHERE ID = P_ID;

END;
/

SHOW ERRORS;

COMMIT;

-- =========================================================
-- 7. PROCEDIMIENTO ELIMINAR
-- =========================================================

CREATE OR REPLACE PROCEDURE SP_ELIMINAR_EMPLEADO(

    P_ID IN NUMBER

)
AS
BEGIN

    DELETE FROM EMPLEADOS_H
    WHERE ID = P_ID;

END;
/

SHOW ERRORS;

COMMIT;

-- =========================================================
-- 8. TRIGGER REGISTRO NUMERO 50
-- =========================================================

CREATE OR REPLACE TRIGGER TRG_REGISTRO_50

AFTER INSERT ON EMPLEADOS_H
FOR EACH ROW

BEGIN

    IF :NEW.ID = 50 THEN

        INSERT INTO LOG_REGISTRO_50 (

            MENSAJE

        )
        VALUES (

            'Se insertó el registro número 50 correctamente'

        );

    END IF;

END;
/

SHOW ERRORS;

COMMIT;

-- =========================================================
-- 9. INSERTAR 50 REGISTROS DE PRUEBA
-- =========================================================

BEGIN

    FOR I IN 1..50 LOOP

        SP_INSERTAR_EMPLEADO(

            'Empleado ' || I,
            'Desarrollador',
            2000 + I

        );

    END LOOP;

    COMMIT;

END;
/

-- =========================================================
-- 10. CONSULTAR EMPLEADOS
-- =========================================================

SELECT *
FROM EMPLEADOS_H
ORDER BY ID;

-- =========================================================
-- 11. CONSULTAR LOG DEL TRIGGER
-- =========================================================

SELECT *
FROM LOG_REGISTRO_50
ORDER BY ID_LOG;

-- =========================================================
-- 12. VERIFICAR OBJETOS VALIDOS
-- =========================================================

SELECT
    OBJECT_NAME,
    OBJECT_TYPE,
    STATUS
FROM USER_OBJECTS
WHERE OBJECT_TYPE IN ('PROCEDURE', 'TRIGGER')
ORDER BY OBJECT_TYPE, OBJECT_NAME;

COMMIT;